[package]
name = "fedibridge"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = ["atproto"]

[workspace.dependencies]
anyhow = { "version" = "1.0.93" }
thiserror = { "version" = "2.0.3" }
